# Generated by Django 5.0 on 2023-12-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_remove_user_id_alter_user_username_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
